export const INSTITUTIONAL_GREEN = "#7D7F6E";
export const INSTITUTIONAL_GREEN_DARK = "#6a6c5d";
export const INSTITUTIONAL_TERRACOTTA = "#B7694E";
export const INSTITUTIONAL_TERRACOTTA_DARK = "#9f4f37";

export const SIDEBAR_GRADIENT = `linear-gradient(180deg, ${INSTITUTIONAL_GREEN} 0%, ${INSTITUTIONAL_GREEN_DARK} 45%, ${INSTITUTIONAL_TERRACOTTA} 100%)`;
export const TITLE_GRADIENT = `linear-gradient(120deg, ${INSTITUTIONAL_GREEN} 0%, ${INSTITUTIONAL_TERRACOTTA} 100%)`;
export const ICON_GRADIENT = `linear-gradient(135deg, ${INSTITUTIONAL_TERRACOTTA}, ${INSTITUTIONAL_GREEN})`;
