export const drawerWidth = 280;
export const collapsedDrawerWidth = 0;

export const ROLE_NAV_MAP: Record<string, string[]> = {
  admin: [
    "dashboard",
    "preinscripciones",
    "carreras",
    "reportes",
    "asistencia",
    "cursoIntro",
    "mensajes",
    "secretaria",
    "bedeles",
    "docentes",
    "tutorias",
    "equivalencias",
    "titulos",
    "coordinacion",
    "jefatura",
    "estudiante",
    "primeraCarga",
  ],
  secretaria: [
    "dashboard",
    "preinscripciones",
    "carreras",
    "reportes",
    "asistencia",
    "cursoIntro",
    "mensajes",
    "secretaria",
    "bedeles",
    "docentes",
    "tutorias",
    "equivalencias",
    "titulos",
    "coordinacion",
    "jefatura",
    "estudiante",
    "primeraCarga",
  ],
  bedel: ["bedeles", "mensajes", "estudiante", "asistencia", "cursoIntro", "primeraCarga", "carreras"],
  docente: ["docentes", "mensajes"],
  tutor: ["tutorias", "mensajes", "estudiante", "equivalencias", "reportes", "cursoIntro"],
  coordinador: ["coordinacion", "mensajes", "estudiante", "reportes", "cursoIntro"],
  jefes: ["jefatura", "mensajes", "reportes"],
  jefa_aaee: ["jefatura", "mensajes", "reportes"],
  consulta: ["dashboard", "reportes", "mensajes"],
  estudiante: ["estudiante", "mensajes"],
  equivalencias: ["equivalencias", "mensajes"],
  titulos: ["titulos", "mensajes"],
  curso_intro: ["cursoIntro", "mensajes"],
};

export const roleLabels: Record<string, string> = {
  admin: "Administrador",
  secretaria: "Secretaría",
  bedel: "Bedelía",
  docente: "Docente",
  tutor: "Tutoría",
  coordinador: "Coordinación",
  jefes: "Jefatura",
  jefa_aaee: "Jefa A.A.E.E.",
  consulta: "Consulta",
  estudiante: "Estudiante",
  equivalencias: "Equivalencias",
  titulos: "Títulos",
  curso_intro: "Curso Intro",
};

export const roleHomeMap: Record<string, string> = {
  admin: "/dashboard",
  secretaria: "/secretaria",
  bedel: "/bedeles",
  docente: "/docentes",
  tutor: "/tutorias",
  coordinador: "/coordinacion",
  jefes: "/jefatura",
  jefa_aaee: "/jefatura",
  consulta: "/dashboard",
  estudiante: "/estudiantes",
  equivalencias: "/equivalencias",
  titulos: "/titulos",
  curso_intro: "/curso-introductorio",
};

export const navButtonSx = {
  borderRadius: 10,
  mx: 2,
  my: 0.5,
  color: "#ffffff",
  "& .MuiListItemIcon-root": { color: "inherit", minWidth: 32 },
  "& .MuiListItemText-primary": { fontWeight: 600, fontSize: 14 },
  "&.Mui-selected": {
    backgroundColor: "rgba(183,105,78,0.35)",
    boxShadow: "0 15px 35px rgba(125,127,110,0.45)",
  },
  "&:hover": {
    backgroundColor: "rgba(125,127,110,0.25)",
  },
};
