# Re-export everything from submodules so that existing imports like
# `from apps.estudiantes.schemas import X` continue to work unchanged.

from apps.estudiantes.schemas.materias import (
    Horario,
    Cuatrimestre,
    MateriaPlan,
    HistorialEstudiante,
)

from apps.estudiantes.schemas.inscripciones import (
    InscripcionCarreraIn,
    InscripcionCarreraOut,
    InscripcionMateriaIn,
    CancelarInscripcionIn,
    CambioComisionIn,
    InscripcionEstado,
    InscripcionEstadoType,
    MateriaOption,
    ComisionOption,
    CargaNotasLookup,
    ComisionResumen,
    MateriaInscriptaItem,
    InscripcionMateriaOut,
    CambioComisionOut,
)

from apps.estudiantes.schemas.mesas import (
    MesaExamenIn,
    MesaExamenOut,
    InscripcionMesaIn,
    InscripcionMesaOut,
    ConstanciaExamenItem,
    MesaResultadoEstudiante,
    MesaPlanillaOut,
    MesaResultadoIn,
    MesaPlanillaUpdateIn,
    MesaPlanillaCierreIn,
)

from apps.estudiantes.schemas.actas import (
    ActaDocenteIn,
    ActaEstudianteIn,
    ActaCreateIn,
    ActaCreateOut,
    ActaMetadataMateria,
    ActaMetadataPlan,
    ActaMetadataProfesorado,
    ActaMetadataDocente,
    ActaMetadataOut,
    OralTopicSchema,
    ActaOralSchema,
    ActaOralListItemSchema,
)

from apps.estudiantes.schemas.regularidad import (
    RegularidadEstudianteOut,
    RegularidadPlanillaOut,
    RegularidadEstudianteIn,
    RegularidadCargaIn,
    RegularidadCierreIn,
    RegularidadRowIn,
    RegularidadImportIn,
    RegularidadItemOut,
)

from apps.estudiantes.schemas.curso_intro import (
    CursoIntroCohorteIn,
    CursoIntroCohorteOut,
    CursoIntroRegistroOut,
    CursoIntroRegistroIn,
    CursoIntroAsistenciaIn,
    CursoIntroCierreIn,
    CursoIntroPendienteOut,
    CursoIntroVentanaOut,
    CursoIntroEstadoOut,
    CursoIntroAutoInscripcionIn,
)

from apps.estudiantes.schemas.equivalencias import (
    EquivalenciaItem,
    PedidoAnaliticoIn,
    PedidoAnaliticoOut,
    PedidoAnaliticoItem,
    PedidoEquivalenciaMateriaIn,
    PedidoEquivalenciaSaveIn,
    PedidoEquivalenciaMateriaOut,
    PedidoEquivalenciaTimeline,
    PedidoEquivalenciaOut,
    PedidoEquivalenciaDocumentacionIn,
    PedidoEquivalenciaEvaluacionMateriaIn,
    PedidoEquivalenciaEvaluacionIn,
    PedidoEquivalenciaTitulosIn,
    PedidoEquivalenciaNotificarIn,
    EquivalenciaDisposicionDetalleIn,
    EquivalenciaDisposicionDetalleOut,
    EquivalenciaDisposicionCreateIn,
    EquivalenciaDisposicionOut,
    EquivalenciaMateriaPendiente,
)

from apps.estudiantes.schemas.estudiantes_admin import (
    RegularidadResumen,
    EstudianteAdminDocumentacion,
    EstudianteAdminListItem,
    EstudianteAdminListResponse,
    EstudianteDocumentacionListItem,
    EstudianteDocumentacionListResponse,
    EstudianteDocumentacionUpdateIn,
    EstudianteDocumentacionBulkUpdateItem,
    EstudianteDocumentacionBulkUpdateIn,
    EstudianteAdminDetail,
    EstudianteAdminUpdateIn,
)

from apps.estudiantes.schemas.trayectoria import (
    EventoTipo,
    TrayectoriaEvento,
    TrayectoriaMesa,
    MateriaSugerida,
    FinalHabilitado,
    RegularidadVigenciaOut,
    CarreraPlanResumen,
    CarreraDetalleResumen,
    EstudianteResumen,
    RecomendacionesOut,
    CartonEvento,
    CartonMateria,
    CartonPlan,
    TrayectoriaOut,
    HorarioMateriaCelda,
    HorarioDia,
    HorarioFranja,
    HorarioCelda,
    HorarioTabla,
)

__all__ = [
    # materias
    "Horario",
    "Cuatrimestre",
    "MateriaPlan",
    "HistorialEstudiante",
    # inscripciones
    "InscripcionCarreraIn",
    "InscripcionCarreraOut",
    "InscripcionMateriaIn",
    "CancelarInscripcionIn",
    "CambioComisionIn",
    "InscripcionEstado",
    "InscripcionEstadoType",
    "MateriaOption",
    "ComisionOption",
    "CargaNotasLookup",
    "ComisionResumen",
    "MateriaInscriptaItem",
    "InscripcionMateriaOut",
    "CambioComisionOut",
    # mesas
    "MesaExamenIn",
    "MesaExamenOut",
    "InscripcionMesaIn",
    "InscripcionMesaOut",
    "ConstanciaExamenItem",
    "MesaResultadoEstudiante",
    "MesaPlanillaOut",
    "MesaResultadoIn",
    "MesaPlanillaUpdateIn",
    "MesaPlanillaCierreIn",
    # actas
    "ActaDocenteIn",
    "ActaEstudianteIn",
    "ActaCreateIn",
    "ActaCreateOut",
    "ActaMetadataMateria",
    "ActaMetadataPlan",
    "ActaMetadataProfesorado",
    "ActaMetadataDocente",
    "ActaMetadataOut",
    "OralTopicSchema",
    "ActaOralSchema",
    "ActaOralListItemSchema",
    # regularidad
    "RegularidadEstudianteOut",
    "RegularidadPlanillaOut",
    "RegularidadEstudianteIn",
    "RegularidadCargaIn",
    "RegularidadCierreIn",
    "RegularidadRowIn",
    "RegularidadImportIn",
    "RegularidadItemOut",
    # curso_intro
    "CursoIntroCohorteIn",
    "CursoIntroCohorteOut",
    "CursoIntroRegistroOut",
    "CursoIntroRegistroIn",
    "CursoIntroAsistenciaIn",
    "CursoIntroCierreIn",
    "CursoIntroPendienteOut",
    "CursoIntroVentanaOut",
    "CursoIntroEstadoOut",
    "CursoIntroAutoInscripcionIn",
    # equivalencias
    "EquivalenciaItem",
    "PedidoAnaliticoIn",
    "PedidoAnaliticoOut",
    "PedidoAnaliticoItem",
    "PedidoEquivalenciaMateriaIn",
    "PedidoEquivalenciaSaveIn",
    "PedidoEquivalenciaMateriaOut",
    "PedidoEquivalenciaTimeline",
    "PedidoEquivalenciaOut",
    "PedidoEquivalenciaDocumentacionIn",
    "PedidoEquivalenciaEvaluacionMateriaIn",
    "PedidoEquivalenciaEvaluacionIn",
    "PedidoEquivalenciaTitulosIn",
    "PedidoEquivalenciaNotificarIn",
    "EquivalenciaDisposicionDetalleIn",
    "EquivalenciaDisposicionDetalleOut",
    "EquivalenciaDisposicionCreateIn",
    "EquivalenciaDisposicionOut",
    "EquivalenciaMateriaPendiente",
    # estudiantes_admin
    "RegularidadResumen",
    "EstudianteAdminDocumentacion",
    "EstudianteAdminListItem",
    "EstudianteAdminListResponse",
    "EstudianteDocumentacionListItem",
    "EstudianteDocumentacionListResponse",
    "EstudianteDocumentacionUpdateIn",
    "EstudianteDocumentacionBulkUpdateItem",
    "EstudianteDocumentacionBulkUpdateIn",
    "EstudianteAdminDetail",
    "EstudianteAdminUpdateIn",
    # trayectoria
    "EventoTipo",
    "TrayectoriaEvento",
    "TrayectoriaMesa",
    "MateriaSugerida",
    "FinalHabilitado",
    "RegularidadVigenciaOut",
    "CarreraPlanResumen",
    "CarreraDetalleResumen",
    "EstudianteResumen",
    "RecomendacionesOut",
    "CartonEvento",
    "CartonMateria",
    "CartonPlan",
    "TrayectoriaOut",
    "HorarioMateriaCelda",
    "HorarioDia",
    "HorarioFranja",
    "HorarioCelda",
    "HorarioTabla",
]
