# Generated by Django 5.2.8 on 2026-05-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_solicitudmesa_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudmesa',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('PRO', 'Mesa Aprobada'), ('REC', 'Rechazada')], default='PEN', max_length=3),
        ),
    ]
